SECONDS_IN_MINUTE = 60
MINUTES_IN_HOUR = 60
SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR
HOURS_IN_DAY = 24
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY

CARS_IN_DAY = 10000

YELLOW_TIME = 3
MIN_GREEN_TIME = 5
MAX_GREEN_TIME = 40

WAITING_TIME_MEMORY_LIMIT = "--waiting-time-memory=1000000"
