SECONDS_IN_MINUTE = 60
MINUTES_IN_HOUR = 60
SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR
HOURS_IN_DAY = 24
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY

CARS_IN_DAY = 1000

YELLOW_TIME = 3
MIN_GREEN_TIME = 3
MAX_GREEN_TIME = 40
